// SOUND — synthesised, not sampled.
//
// Every sound in this game is generated by WebAudio at runtime. No files, no
// downloads, no licensing, no CDN, and it adds nothing to the 25-dollar budget
// or to the APK size. It also means a hit can be pitched by how hard it landed
// instead of picking from three canned thuds.
//
// Nothing starts until the first tap: browsers suspend audio contexts created
// before a user gesture, and a game that boots silent and stays silent is the
// single most common way this goes wrong.

let ctx = null;
let master = null;
let musicGain = null;
let sfxGain = null;
let started = false;

export const SFX = {
  enabled: true,
  musicOn: true,

  init() {
    if (ctx) return;
    const AC = window.AudioContext || window.webkitAudioContext;
    if (!AC) return;
    ctx = new AC();
    master = ctx.createGain();
    master.gain.value = 0.85;
    master.connect(ctx.destination);

    sfxGain = ctx.createGain();
    sfxGain.gain.value = 0.9;
    sfxGain.connect(master);

    musicGain = ctx.createGain();
    musicGain.gain.value = 0.0;
    musicGain.connect(master);
  },

  // Call from a real user gesture.
  resume() {
    this.init();
    if (!ctx) return;
    if (ctx.state === 'suspended') ctx.resume();
    started = true;
  },

  get ready() { return !!ctx && started && this.enabled; },
  get time() { return ctx ? ctx.currentTime : 0; },

  // The generated soundtrack (js/music.js) hangs its own fader off `master`,
  // so one volume and one context still cover everything. It deliberately does
  // NOT share `musicGain`: the synthesised score owns that, and stopMusic()
  // ramps it to zero — which would cut the files off mid-bar.
  bus() {
    this.init();
    return ctx ? { ctx, master } : null;
  },
};

// ---------------------------------------------------------------- primitives
function env(node, t, a, d, peak = 1) {
  const g = ctx.createGain();
  g.gain.setValueAtTime(0.0001, t);
  g.gain.exponentialRampToValueAtTime(Math.max(0.0001, peak), t + a);
  g.gain.exponentialRampToValueAtTime(0.0001, t + a + d);
  node.connect(g);
  return g;
}

function tone(freq, t, dur, type = 'sine', peak = 0.3, bend = 0, dest = null) {
  const o = ctx.createOscillator();
  o.type = type;
  o.frequency.setValueAtTime(freq, t);
  if (bend) o.frequency.exponentialRampToValueAtTime(Math.max(20, freq + bend), t + dur);
  const g = env(o, t, 0.005, dur, peak);
  g.connect(dest || sfxGain);
  o.start(t);
  o.stop(t + dur + 0.06);
  return o;
}

// One reusable noise buffer. Making a new one per hit allocates for no reason.
let noiseBuf = null;
function noise(t, dur, peak = 0.3, filterHz = 2000, q = 1, type = 'lowpass', dest = null) {
  if (!noiseBuf) {
    noiseBuf = ctx.createBuffer(1, ctx.sampleRate * 1.2, ctx.sampleRate);
    const d = noiseBuf.getChannelData(0);
    for (let i = 0; i < d.length; i++) d[i] = Math.random() * 2 - 1;
  }
  const s = ctx.createBufferSource();
  s.buffer = noiseBuf;
  s.playbackRate.value = 0.8 + Math.random() * 0.4;
  const f = ctx.createBiquadFilter();
  f.type = type;
  f.frequency.setValueAtTime(filterHz, t);
  f.Q.value = q;
  s.connect(f);
  const g = env(f, t, 0.004, dur, peak);
  g.connect(dest || sfxGain);
  s.start(t, Math.random() * 0.4);
  s.stop(t + dur + 0.06);
  return { src: s, filter: f };
}

// ---------------------------------------------------------------- the sounds
const S = SFX;

// `power` 0..1 scales pitch and weight, so a heavy lands heavier than a jab
// without needing a second sound.
S.hit = function (power = 0.5) {
  if (!this.ready) return;
  const t = ctx.currentTime;
  const p = Math.max(0, Math.min(1, power));
  // body: a short pitched thump
  tone(150 - p * 60, t, 0.10 + p * 0.10, 'sine', 0.34 + p * 0.24, -90);
  // crack: filtered noise burst
  const { filter } = noise(t, 0.07 + p * 0.06, 0.24 + p * 0.2, 1200 + p * 2200, 1.4, 'bandpass');
  filter.frequency.exponentialRampToValueAtTime(400, t + 0.09);
  if (p > 0.6) tone(70, t + 0.01, 0.20, 'triangle', 0.30, -30);   // extra weight
};

S.whiff = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;
  const { filter } = noise(t, 0.13, 0.10, 900, 2, 'bandpass');
  filter.frequency.setValueAtTime(400, t);
  filter.frequency.exponentialRampToValueAtTime(2600, t + 0.12);
};

S.jump = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;
  tone(260, t, 0.13, 'sine', 0.16, 220);
};

S.land = function (hard = 0.4) {
  if (!this.ready) return;
  const t = ctx.currentTime;
  noise(t, 0.09, 0.10 + hard * 0.14, 500, 1, 'lowpass');
  tone(90, t, 0.09, 'sine', 0.14 + hard * 0.14, -30);
};

S.dodge = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;
  const { filter } = noise(t, 0.16, 0.13, 1800, 3, 'bandpass');
  filter.frequency.setValueAtTime(2600, t);
  filter.frequency.exponentialRampToValueAtTime(500, t + 0.15);
};

// Picking something up and throwing it are the two most repeated actions in the
// game after swinging, and both used to be one blip each: grab was a single
// 60ms square tone at 0.09, which next to a 0.475 hit was effectively silent.
//
// They are now built from what is being lifted. `style` comes straight from
// PROP_STYLES in weapons.js so the tables cannot drift apart, and `mass` from
// the body itself — a filing cabinet and a coffee mug should not leave your
// hands the same way. Mass sets the pitch and the length; style adds the
// material on top.
const GRAB_TINT = {
  //          thunk Hz   scuff Hz   tint
  glass:    { f: 300, air: 3200, tink: 2400 },   // monitor, mug, cooler
  heavy:    { f: 120, air: 900,  tink: 0 },      // printer, cabinet, coffee machine
  light:    { f: 380, air: 4200, tink: 0 },      // papers, phone, bin
  sweep:    { f: 210, air: 1800, tink: 700 },    // chair, plant
  spray:    { f: 190, air: 1400, tink: 1500 },   // extinguisher
  person:   { f: 160, air: 2200, tink: 0 },      // a colleague, hoisted
};

/**
 * style  a PROP_STYLES style ('glass'|'heavy'|'light'|'sweep'|'spray') or
 *        'person'. Anything unknown falls back to 'light'.
 * mass   the body's mass; 0.4 (a mug) to 5.5 (a filing cabinet).
 */
S.grab = function (style = 'light', mass = 1) {
  if (!this.ready) return;
  const t = ctx.currentTime;
  const k = GRAB_TINT[style] || GRAB_TINT.light;
  const m = Math.max(0.3, Math.min(6, mass));
  const heft = Math.min(1, m / 4);                  // 0 = a mug, 1 = a cabinet

  // hands closing on the thing: a short filtered scuff
  const { filter } = noise(t, 0.09 + heft * 0.06, 0.085 + heft * 0.05, k.air, 1.2, 'bandpass');
  filter.frequency.exponentialRampToValueAtTime(Math.max(200, k.air * 0.4), t + 0.09);

  // and its weight arriving, pitched down by how heavy it is
  tone(k.f / (0.7 + heft * 0.6), t + 0.012, 0.09 + heft * 0.07, 'triangle', 0.11 + heft * 0.06, -40);

  // the material speaking up: glass tinks, a chair rattles, a cabinet does not
  if (k.tink) tone(k.tink * (0.9 + Math.random() * 0.2), t + 0.03, 0.07, 'sine', 0.05, -300);
};

/**
 * power  0..1, how hard it went out
 * style  as above
 * mass   as above
 */
S.throw_ = function (power = 0.7, style = 'light', mass = 1) {
  if (!this.ready) return;
  const t = ctx.currentTime;
  const k = GRAB_TINT[style] || GRAB_TINT.light;
  const m = Math.max(0.3, Math.min(6, mass));
  const heft = Math.min(1, m / 4);
  const p = Math.max(0, Math.min(1, power));

  // The whoosh. Heavier things cut the air lower and for longer, and the sweep
  // direction is what makes it read as leaving rather than arriving.
  const dur = 0.16 + heft * 0.12;
  const from = (500 + p * 400) / (0.8 + heft * 0.9);
  const { filter } = noise(t, dur, 0.12 + p * 0.07, from, 2.5, 'bandpass');
  filter.frequency.exponentialRampToValueAtTime(from * (3.2 - heft * 1.4), t + dur * 0.9);

  // the release itself - a low thump you feel more than hear
  tone(90 + heft * 40, t, 0.10 + heft * 0.05, 'sine', 0.10 + heft * 0.07, -30);

  // Same random detune the noise buffer already uses, applied to the tint, so
  // twenty throws in a row are not twenty identical sounds.
  if (k.tink) tone(k.tink * (0.85 + Math.random() * 0.3), t + 0.02, 0.06, 'sine', 0.04, -400);
};

// Destruction, tinted by material.
S.smash = function (material = 'plastic', size = 0.5) {
  if (!this.ready) return;
  const t = ctx.currentTime;
  const p = Math.max(0, Math.min(1, size));
  if (material === 'glass') {
    for (let i = 0; i < 9; i++) {
      const tt = t + Math.random() * 0.16;
      tone(1600 + Math.random() * 2600, tt, 0.10 + Math.random() * 0.14, 'sine', 0.07, -600);
    }
    noise(t, 0.22, 0.16, 5200, 1, 'highpass');
  } else if (material === 'paper') {
    const { filter } = noise(t, 0.30, 0.13, 4200, 0.8, 'highpass');
    filter.frequency.exponentialRampToValueAtTime(1400, t + 0.28);
  } else if (material === 'metal') {
    noise(t, 0.14, 0.16, 3000, 1, 'bandpass');
    tone(320, t, 0.28, 'triangle', 0.14, -140);
    tone(690, t + 0.01, 0.22, 'triangle', 0.09, -260);
  } else {                                   // plastic / generic
    noise(t, 0.16, 0.18 + p * 0.1, 1600, 1, 'lowpass');
    tone(120, t, 0.13, 'square', 0.13, -60);
  }
};

S.coin = function (chain = 1) {
  if (!this.ready) return;
  const t = ctx.currentTime;
  // pentatonic, climbing with the chain so a long combo literally sounds better
  const scale = [523.25, 587.33, 659.25, 783.99, 880.0];
  const n = scale[Math.min(scale.length - 1, chain - 1)] || 880;
  tone(n, t, 0.10, 'triangle', 0.16);
  tone(n * 2, t + 0.015, 0.09, 'sine', 0.09);
};

S.chain = function (n) {
  if (!this.ready) return;
  const t = ctx.currentTime;
  const base = 330 * Math.pow(1.0595, Math.min(24, n * 2));
  tone(base, t, 0.13, 'triangle', 0.17);
  tone(base * 1.5, t + 0.05, 0.15, 'sine', 0.12);
  tone(base * 2, t + 0.10, 0.20, 'sine', 0.09);
};

// One gulp: a resonant low burst with a pitch that rises, because a cup empties
// as you drink it and the air column above the coffee gets longer.
function gulp(t, pitch, loud) {
  const { filter } = noise(t, 0.085, loud * 0.55, 320, 6, 'bandpass');
  filter.frequency.setValueAtTime(pitch * 2.2, t);
  filter.frequency.exponentialRampToValueAtTime(pitch * 1.2, t + 0.08);
  tone(pitch, t, 0.075, 'sine', loud, pitch * 0.35);
}

// The coffee machine used to be the whole sound: a 0.55s dispense and a ding,
// with nobody actually drinking anything. It now runs the full beat - dispense,
// three gulps, the exhale, and the cup going down - because the 12 second boost
// it grants is worth more than a ding.
//
// It has to finish inside the 0.9s per-cup gate in main.js or a second cup
// starts while the first is still being swallowed, so the whole thing is 0.95s.
S.coffee = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;

  // dispense
  const { filter } = noise(t, 0.30, 0.085, 900, 0.7, 'bandpass');
  filter.frequency.setValueAtTime(600, t);
  filter.frequency.linearRampToValueAtTime(1500, t + 0.28);

  // three gulps, climbing
  gulp(t + 0.34, 150, 0.11);
  gulp(t + 0.50, 168, 0.105);
  gulp(t + 0.65, 188, 0.09);

  // "aaah" - filtered breath, and the cup set down on the desk
  const { filter: ex } = noise(t + 0.80, 0.17, 0.055, 1100, 0.9, 'bandpass');
  ex.frequency.setValueAtTime(1300, t + 0.80);
  ex.frequency.exponentialRampToValueAtTime(520, t + 0.95);
  tone(2100, t + 0.90, 0.05, 'sine', 0.045, -700);
};

// ---------------------------------------------------------------- footsteps
//
// Only the boss has these, and they are distance-attenuated on purpose: hearing
// him crossing the floor before he is on screen is the point of having them at
// all. Everyone else in the office would just be noise - there are six of them
// and they mill about constantly.
S.step = function (weight = 1, dx = 0) {
  if (!this.ready) return;
  const w = Math.max(0.2, Math.min(1.4, weight));

  // A level is 4400px wide; a footstep should be gone long before that.
  const near = 1 - Math.min(1, Math.abs(dx) / 620);
  if (near <= 0.03) return;            // too far to be worth scheduling nodes for
  const t = ctx.currentTime;

  const out = ctx.createGain();
  out.gain.value = near * near;        // squared, so he reads as close only when he is
  let tail = out;
  if (ctx.createStereoPanner) {
    const pan = ctx.createStereoPanner();
    pan.pan.value = Math.max(-0.7, Math.min(0.7, dx / 380));
    out.connect(pan);
    tail = pan;
  }
  tail.connect(sfxGain);

  // heel, then the scuff of the sole. The pitch wanders a little so a walk
  // across the office is not a metronome.
  const v = 0.92 + Math.random() * 0.16;
  tone(72 * v, t, 0.10 + w * 0.04, 'sine', 0.30 * w, -26, out);
  noise(t + 0.008, 0.055, 0.10 * w, 420 * v, 1, 'lowpass', out);
  if (w > 0.85) tone(140 * v, t + 0.01, 0.07, 'triangle', 0.06, -40, out);
};

S.alarm = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;
  for (let i = 0; i < 3; i++) {
    tone(760, t + i * 0.24, 0.14, 'square', 0.11);
    tone(560, t + i * 0.24 + 0.12, 0.12, 'square', 0.11);
  }
};

S.bossRoar = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;
  tone(90, t, 0.65, 'sawtooth', 0.20, -40);
  tone(136, t + 0.02, 0.55, 'sawtooth', 0.13, -50);
  const { filter } = noise(t, 0.6, 0.13, 700, 1.2, 'lowpass');
  filter.frequency.exponentialRampToValueAtTime(200, t + 0.55);
};

S.ui = function (up = true) {
  if (!this.ready) return;
  const t = ctx.currentTime;
  tone(up ? 660 : 440, t, 0.07, 'triangle', 0.11, up ? 120 : -80);
};

S.promote = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;
  [523.25, 659.25, 783.99, 1046.5].forEach((f, i) =>
    tone(f, t + i * 0.11, 0.32, 'triangle', 0.15));
};

// ---------------------------------------------------------------- voices
//
// Cartoon gibberish, not speech. Every character yelp, scream and swear in this
// game is two oscillators through a pair of bandpass filters parked on vowel
// formants — the Animal Crossing / Simlish trick. It is here rather than in a
// pack of recordings for four reasons that all matter to this project:
//
//   * The music model cannot do it. It is instrumental by design; every prompt
//     in the Studio packs literally ends "no vocals".
//   * Recorded voice lines are the one asset class that cannot be generated
//     free, and the whole budget is the 25-dollar Play fee.
//   * A recording is one performance. This is pitched per character and per
//     hit, so the boss and the intern are audibly different people and the
//     fifth hit of a combo does not replay the fourth.
//   * Swearing that is actually gibberish under a censor bleep is funnier than
//     swearing, and it cannot fail a store rating or need translating.
//
// A "vowel" here is just the first two formants. Sliding the pitch across a
// syllable is what makes it read as a voice rather than a synth blip: falling
// for pain, rising for surprise, wobbling for a rant.

const VOWELS = [
  [730, 1090],   // a
  [530, 1840],   // e
  [270, 2290],   // i
  [570, 840],    // o
  [300, 870],    // u
];

// f0 is the speaking pitch, fscale stretches the formants (a smaller head has
// higher formants, which is what separates male from female far more than pitch
// alone does), rate is how fast they talk.
const VOICES = {
  player:  { f0: 132, fscale: 1.00, wave: 'sawtooth', rate: 1.00 },
  boss:    { f0: 92,  fscale: 0.90, wave: 'sawtooth', rate: 0.86 },
  omar:    { f0: 158, fscale: 1.06, wave: 'square',   rate: 1.30 },  // nervous, fast
  rita:    { f0: 214, fscale: 1.18, wave: 'sawtooth', rate: 1.16 },  // sharp
  sami:    { f0: 104, fscale: 0.96, wave: 'square',   rate: 0.78 },  // slow, dopey
  male:    { f0: 124, fscale: 1.00, wave: 'sawtooth', rate: 1.00 },
  male2:   { f0: 148, fscale: 1.04, wave: 'square',   rate: 1.12 },
  female:  { f0: 206, fscale: 1.16, wave: 'sawtooth', rate: 1.06 },
  female2: { f0: 232, fscale: 1.22, wave: 'square',   rate: 1.20 },
};

// The named cast in office.js. Anyone else falls through to the hash below, so
// adding a coworker never leaves them mute.
const CAST_VOICE = {
  SAMI: 'sami', RITA: 'rita', OMAR: 'omar',
  LEA: 'female', KARIM: 'male2', NOUR: 'female2', DALIA: 'female',
  'MR. HALEY': 'boss', PLAYER: 'player', BOSS: 'boss',
};

function voiceOf(who) {
  if (!who) return VOICES.male;
  const k = String(who).toUpperCase();
  if (CAST_VOICE[k]) return VOICES[CAST_VOICE[k]];
  if (VOICES[k.toLowerCase()]) return VOICES[k.toLowerCase()];
  // Unknown name: pick from the hash so the same person keeps the same voice
  // for the whole shift rather than changing every time they are hit.
  let h = 0;
  for (let i = 0; i < k.length; i++) h = (h * 31 + k.charCodeAt(i)) | 0;
  return [VOICES.male, VOICES.female, VOICES.male2, VOICES.female2][Math.abs(h) % 4];
}

// One syllable: a pitched buzz shaped by two formants, gliding from f1 to f2.
function syllable(t, v, dur, fFrom, fTo, vowel, loud, wobble = 0) {
  const [F1, F2] = VOWELS[vowel % VOWELS.length];
  const osc = ctx.createOscillator();
  osc.type = v.wave;
  osc.frequency.setValueAtTime(Math.max(40, fFrom), t);
  osc.frequency.exponentialRampToValueAtTime(Math.max(40, fTo), t + dur);

  // vibrato — a scream without it sounds like a car alarm
  let lfo = null;
  if (wobble > 0) {
    lfo = ctx.createOscillator();
    lfo.frequency.value = 11 + Math.random() * 5;
    const amt = ctx.createGain();
    amt.gain.value = fFrom * wobble;
    lfo.connect(amt);
    amt.connect(osc.frequency);
    lfo.start(t);
    lfo.stop(t + dur + 0.05);
  }

  const out = ctx.createGain();
  out.gain.setValueAtTime(0.0001, t);
  out.gain.exponentialRampToValueAtTime(Math.max(0.0001, loud), t + Math.min(0.02, dur * 0.25));
  out.gain.exponentialRampToValueAtTime(0.0001, t + dur);
  out.connect(sfxGain);

  for (const [f, g] of [[F1, 1.0], [F2, 0.55]]) {
    const bp = ctx.createBiquadFilter();
    bp.type = 'bandpass';
    bp.frequency.value = f * v.fscale;
    bp.Q.value = 7;
    const lvl = ctx.createGain();
    lvl.gain.value = g;
    osc.connect(bp); bp.connect(lvl); lvl.connect(out);
  }

  osc.start(t);
  osc.stop(t + dur + 0.05);
}

// A censor bleep. Sits over the middle of a swear so the gibberish underneath
// is implied rather than heard, which is the whole joke.
function bleep(t, dur, loud = 0.13) {
  const o = ctx.createOscillator();
  o.type = 'square';
  o.frequency.value = 1000;
  const g = ctx.createGain();
  g.gain.setValueAtTime(0.0001, t);
  g.gain.exponentialRampToValueAtTime(loud, t + 0.008);
  g.gain.setValueAtTime(loud, t + dur - 0.01);
  g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
  o.connect(g); g.connect(sfxGain);
  o.start(t); o.stop(t + dur + 0.02);
}

// One character never talks over themselves: a five-hit combo would otherwise
// stack five screams into a wall of noise.
const voiceBusy = new Map();

/**
 * who   'player' | 'boss' | a coworker's name — anything unknown gets a
 *        stable voice from its hash
 * kind  'hurt' | 'scream' | 'curse' | 'mutter'
 */
SFX.voice = function (who, kind = 'hurt', power = 0.5) {
  if (!this.ready || !this.enabled) return;
  const v = voiceOf(who);
  const now = ctx.currentTime;
  const key = String(who || '?').toUpperCase();
  if ((voiceBusy.get(key) || 0) > now) return;

  const p = Math.max(0, Math.min(1, power));
  const rnd = (a, b) => a + Math.random() * (b - a);
  const pick = () => Math.floor(Math.random() * VOWELS.length);
  let t = now + 0.01;
  let busy = 0.3;

  // LEVELS. The first pass mixed these as a background reaction layer and they
  // measured 0.04-0.13 peak on the master bus against hit(1.0) at 0.48 - about
  // ten times under. In isolation that is audible; in play, under a hit, a
  // smash and a music bed, it is not there at all, and the first thing anyone
  // said about them was that they could not hear them. These numbers are set
  // from measurement, not taste: hurt ~0.16, scream ~0.22, curse ~0.20, mutter
  // ~0.09, which puts a yelp alongside smash (0.19) and bossRoar (0.16) and
  // still keeps it under a punch. The bandpass pair at Q=7 throws away most of
  // the oscillator's energy, which is why the raw numbers look so hot.
  if (kind === 'scream') {
    // one long vowel, up then down, wobbling
    const dur = rnd(0.55, 0.95) / v.rate;
    const top = v.f0 * rnd(2.0, 2.6);
    syllable(t, v, dur * 0.35, v.f0 * 1.3, top, Math.random() < 0.5 ? 0 : 1, 0.50 + p * 0.25, 0.05);
    syllable(t + dur * 0.34, v, dur * 0.66, top, v.f0 * 1.1, 0, 0.48 + p * 0.25, 0.07);
    busy = dur + 0.35;
  } else if (kind === 'curse') {
    // a short rant, bleeped through the middle
    const n = 3 + Math.floor(Math.random() * 3);
    const step = rnd(0.10, 0.14) / v.rate;
    for (let i = 0; i < n; i++) {
      const f = v.f0 * rnd(1.0, 1.6);
      syllable(t, v, step * 0.85, f, f * rnd(0.72, 1.25), pick(), 0.26, 0.02);
      t += step;
    }
    const span = n * step;
    bleep(now + 0.01 + span * 0.22, span * 0.62);
    busy = span + 0.4;
  } else if (kind === 'mutter') {
    // Grumbling under the breath: slow, no bleep, and quieter than a yelp — but
    // the first version dropped the pitch so far (0.72x of an already low f0)
    // that the boss's fundamental fell below the formant band and almost
    // nothing came through: 0.014 peak on the master bus, inaudible under
    // music. Staying nearer the speaking pitch is what makes it a grumble you
    // can actually hear rather than a gain problem.
    const n = 3 + Math.floor(Math.random() * 4);
    const step = rnd(0.11, 0.16) / v.rate;
    for (let i = 0; i < n; i++) {
      const f = v.f0 * rnd(0.86, 1.02);
      syllable(t, v, step * 0.8, f, f * rnd(0.85, 1.05), pick(), 0.50, 0.015);
      t += step;
    }
    busy = n * step + 0.25;
  } else {
    // hurt: one or two falling syllables — "ow", "ar-gh"
    const n = Math.random() < 0.35 ? 2 : 1;
    const step = rnd(0.10, 0.15) / v.rate;
    for (let i = 0; i < n; i++) {
      const f = v.f0 * rnd(1.5, 2.1) * (1 + p * 0.25);
      syllable(t, v, step * 0.95, f, f * rnd(0.55, 0.72), i ? pick() : (Math.random() < 0.6 ? 0 : 3),
               0.55 + p * 0.33, 0.03);
      t += step;
    }
    busy = n * step + 0.18;
  }

  voiceBusy.set(key, now + busy);
};

// ---------------------------------------------------------------- music
//
// "Original comedic cartoon soundtrack: fast tempo, playful brass, pizzicato
// strings, quirky percussion, exaggerated slapstick energy, seamless loop, no
// vocals, completely original."
//
// Synthesised, not sampled — which makes it original by construction, costs
// nothing, adds zero bytes, and lets the arrangement react to the game: the
// tempo climbs and the brass gets ruder as the boss's anger rises.
//
// Four voices, scheduled a little ahead of playback:
//   PIZZ   plucked bass — very short decay, that dry "boing" walk
//   BRASS  sawtooth through a fast filter sweep — staccato stabs on offbeats
//   XYLO   bright triangle blips — the slapstick melody
//   PERC   woodblock, shaker, kick, snap
//
// 8 sections x 4 bars at ~150bpm is a hair under a minute, and the loop point
// is bar 0 of section 0, so it joins seamlessly.

let musicTimer = null;
let step = 0;             // 16th notes since the loop began
let nextTime = 0;
let tension = 0;

const BPM = 150;
const SIXTEENTH = () => 60 / (BPM + tension * 26) / 4;
const BARS = 32;
const STEPS = BARS * 16;

// D natural minor with a comedy flat-five. Semitones from D2.
const D2 = 73.42;
const semi = n => D2 * Math.pow(2, n / 12);

// ── the walking pizzicato bass — the engine of the whole thing ──────────────
const BASS = [
  0, 0, 7, 0, 3, 3, 10, 3, 5, 5, 12, 5, 3, 3, 2, 1,
  0, 0, 7, 0, 3, 3, 10, 3, 5, 7, 8, 9, 10, 11, 12, 13,
  -2, -2, 5, -2, 1, 1, 8, 1, 3, 3, 10, 3, 5, 5, 4, 3,
  0, 0, 7, 0, 3, 3, 10, 3, 5, 5, 12, 5, 7, 6, 5, -1,
];

// ── brass stabs: sparse, rude, always slightly late ────────────────────────
// [step within the 64-step section, chord root]
const STABS = [
  [6, 12], [14, 15], [22, 12], [30, 10],
  [38, 12], [46, 17], [54, 15], [62, 19],
];

// ── the xylophone tune, 16ths, null = rest ─────────────────────────────────
const TUNE = [
  24, null, 26, 27, null, 24, null, 22, 24, null, 27, null, 29, null, 27, 26,
  24, null, 22, 20, null, 22, null, 24, 22, null, 20, null, 19, null, null, null,
  27, null, 29, 31, null, 29, null, 27, 26, null, 24, null, 22, null, 24, 26,
  24, null, null, 19, null, 22, null, 24, 26, 27, 26, 24, 22, 20, 19, null,
];

function pluck(t, freq, dur, peak, type = 'triangle') {
  const o = ctx.createOscillator();
  o.type = type;
  o.frequency.setValueAtTime(freq, t);
  const g = ctx.createGain();
  g.gain.setValueAtTime(0.0001, t);
  g.gain.exponentialRampToValueAtTime(peak, t + 0.006);
  g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
  o.connect(g); g.connect(musicGain);
  o.start(t); o.stop(t + dur + 0.04);
}

function brass(t, freq, dur, peak) {
  // sawtooth through a filter that snaps open — the classic cartoon parp
  const o = ctx.createOscillator();
  o.type = 'sawtooth';
  o.frequency.setValueAtTime(freq * 0.985, t);
  o.frequency.linearRampToValueAtTime(freq, t + 0.05);
  const f = ctx.createBiquadFilter();
  f.type = 'lowpass';
  f.Q.value = 7;
  f.frequency.setValueAtTime(freq * 1.2, t);
  f.frequency.exponentialRampToValueAtTime(Math.min(7000, freq * 7), t + 0.05);
  f.frequency.exponentialRampToValueAtTime(freq * 1.6, t + dur);
  const g = ctx.createGain();
  g.gain.setValueAtTime(0.0001, t);
  g.gain.exponentialRampToValueAtTime(peak, t + 0.02);
  g.gain.setValueAtTime(peak, t + dur * 0.55);
  g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
  o.connect(f); f.connect(g); g.connect(musicGain);
  o.start(t); o.stop(t + dur + 0.05);
}

function woodblock(t, peak, hz = 1500) {
  const o = ctx.createOscillator();
  o.type = 'square';
  o.frequency.setValueAtTime(hz, t);
  o.frequency.exponentialRampToValueAtTime(hz * 0.55, t + 0.03);
  const g = ctx.createGain();
  g.gain.setValueAtTime(peak, t);
  g.gain.exponentialRampToValueAtTime(0.0001, t + 0.05);
  o.connect(g); g.connect(musicGain);
  o.start(t); o.stop(t + 0.07);
}

S.setTension = function (v) { tension = Math.max(0, Math.min(1, v)); };

S.startMusic = function () {
  if (!ctx || musicTimer || !this.musicOn) return;
  musicGain.gain.cancelScheduledValues(ctx.currentTime);
  musicGain.gain.setValueAtTime(0.0001, ctx.currentTime);
  musicGain.gain.exponentialRampToValueAtTime(0.55, ctx.currentTime + 1.2);
  nextTime = ctx.currentTime + 0.12;
  musicTimer = setInterval(() => this._pump(), 45);
};

S.stopMusic = function () {
  if (musicTimer) { clearInterval(musicTimer); musicTimer = null; }
  if (musicGain && ctx) {
    musicGain.gain.cancelScheduledValues(ctx.currentTime);
    musicGain.gain.setValueAtTime(musicGain.gain.value, ctx.currentTime);
    musicGain.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + 0.5);
  }
};

S._pump = function () {
  if (!ctx) return;
  const sp = SIXTEENTH();
  while (nextTime < ctx.currentTime + 0.30) {
    const t = nextTime;
    const s16 = step % STEPS;          // position in the whole loop
    const sec = Math.floor(s16 / 64);  // which 4-bar section
    const p = s16 % 64;                // position in the section
    const beat = p % 4;

    // ---- pizzicato bass, every 8th ----
    if (p % 2 === 0) {
      const n = BASS[(sec % 4) * 16 + (p >> 2)] ?? 0;
      pluck(t, semi(n), sp * 1.7, 0.30, 'triangle');
      pluck(t, semi(n) * 2.01, sp * 0.9, 0.07, 'sine');   // string body
    }

    // ---- brass stabs ----
    for (const [at, note] of STABS) {
      if (p !== at) continue;
      const loud = 0.11 + tension * 0.07;
      brass(t, semi(note), sp * 2.4, loud);
      brass(t, semi(note + 7), sp * 2.2, loud * 0.55);
      if (tension > 0.55) brass(t, semi(note + 3), sp * 2.0, loud * 0.4);
    }

    // ---- xylophone tune: sections 1 and 3 carry it ----
    if (sec % 2 === 1) {
      const n = TUNE[p];
      if (n !== null && n !== undefined) {
        pluck(t, semi(n), sp * 2.2, 0.10, 'triangle');
        pluck(t, semi(n) * 2, sp * 1.1, 0.045, 'sine');
      }
    }

    // ---- percussion ----
    if (p % 8 === 0) {                                    // kick
      const k = ctx.createOscillator();
      k.type = 'sine';
      k.frequency.setValueAtTime(140, t);
      k.frequency.exponentialRampToValueAtTime(46, t + 0.1);
      const kg = ctx.createGain();
      kg.gain.setValueAtTime(0.0001, t);
      kg.gain.exponentialRampToValueAtTime(0.30, t + 0.006);
      kg.gain.exponentialRampToValueAtTime(0.0001, t + 0.16);
      k.connect(kg); kg.connect(musicGain);
      k.start(t); k.stop(t + 0.2);
    }
    if (p % 8 === 4) woodblock(t, 0.16, 1200);            // backbeat block
    if (beat === 2) woodblock(t, 0.05, 2400);             // shaker-ish tick
    if (p === 62 && sec % 2 === 1) {                       // slapstick fill
      for (let i = 0; i < 4; i++) woodblock(t + i * sp * 0.5, 0.13, 900 + i * 420);
    }

    nextTime += sp;
    step++;
  }
};
