// SOUND — synthesised, not sampled.
//
// Every sound in this game is generated by WebAudio at runtime. No files, no
// downloads, no licensing, no CDN, and it adds nothing to the 25-dollar budget
// or to the APK size. It also means a hit can be pitched by how hard it landed
// instead of picking from three canned thuds.
//
// Nothing starts until the first tap: browsers suspend audio contexts created
// before a user gesture, and a game that boots silent and stays silent is the
// single most common way this goes wrong.

let ctx = null;
let master = null;
let musicGain = null;
let sfxGain = null;
let started = false;

export const SFX = {
  enabled: true,
  musicOn: true,

  init() {
    if (ctx) return;
    const AC = window.AudioContext || window.webkitAudioContext;
    if (!AC) return;
    ctx = new AC();
    master = ctx.createGain();
    master.gain.value = 0.85;
    master.connect(ctx.destination);

    sfxGain = ctx.createGain();
    sfxGain.gain.value = 0.9;
    sfxGain.connect(master);

    musicGain = ctx.createGain();
    musicGain.gain.value = 0.0;
    musicGain.connect(master);
  },

  // Call from a real user gesture.
  resume() {
    this.init();
    if (!ctx) return;
    if (ctx.state === 'suspended') ctx.resume();
    started = true;
  },

  get ready() { return !!ctx && started && this.enabled; },
  get time() { return ctx ? ctx.currentTime : 0; },
};

// ---------------------------------------------------------------- primitives
function env(node, t, a, d, peak = 1) {
  const g = ctx.createGain();
  g.gain.setValueAtTime(0.0001, t);
  g.gain.exponentialRampToValueAtTime(Math.max(0.0001, peak), t + a);
  g.gain.exponentialRampToValueAtTime(0.0001, t + a + d);
  node.connect(g);
  return g;
}

function tone(freq, t, dur, type = 'sine', peak = 0.3, bend = 0) {
  const o = ctx.createOscillator();
  o.type = type;
  o.frequency.setValueAtTime(freq, t);
  if (bend) o.frequency.exponentialRampToValueAtTime(Math.max(20, freq + bend), t + dur);
  const g = env(o, t, 0.005, dur, peak);
  g.connect(sfxGain);
  o.start(t);
  o.stop(t + dur + 0.06);
  return o;
}

// One reusable noise buffer. Making a new one per hit allocates for no reason.
let noiseBuf = null;
function noise(t, dur, peak = 0.3, filterHz = 2000, q = 1, type = 'lowpass') {
  if (!noiseBuf) {
    noiseBuf = ctx.createBuffer(1, ctx.sampleRate * 1.2, ctx.sampleRate);
    const d = noiseBuf.getChannelData(0);
    for (let i = 0; i < d.length; i++) d[i] = Math.random() * 2 - 1;
  }
  const s = ctx.createBufferSource();
  s.buffer = noiseBuf;
  s.playbackRate.value = 0.8 + Math.random() * 0.4;
  const f = ctx.createBiquadFilter();
  f.type = type;
  f.frequency.setValueAtTime(filterHz, t);
  f.Q.value = q;
  s.connect(f);
  const g = env(f, t, 0.004, dur, peak);
  g.connect(sfxGain);
  s.start(t, Math.random() * 0.4);
  s.stop(t + dur + 0.06);
  return { src: s, filter: f };
}

// ---------------------------------------------------------------- the sounds
const S = SFX;

// `power` 0..1 scales pitch and weight, so a heavy lands heavier than a jab
// without needing a second sound.
S.hit = function (power = 0.5) {
  if (!this.ready) return;
  const t = ctx.currentTime;
  const p = Math.max(0, Math.min(1, power));
  // body: a short pitched thump
  tone(150 - p * 60, t, 0.10 + p * 0.10, 'sine', 0.34 + p * 0.24, -90);
  // crack: filtered noise burst
  const { filter } = noise(t, 0.07 + p * 0.06, 0.24 + p * 0.2, 1200 + p * 2200, 1.4, 'bandpass');
  filter.frequency.exponentialRampToValueAtTime(400, t + 0.09);
  if (p > 0.6) tone(70, t + 0.01, 0.20, 'triangle', 0.30, -30);   // extra weight
};

S.whiff = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;
  const { filter } = noise(t, 0.13, 0.10, 900, 2, 'bandpass');
  filter.frequency.setValueAtTime(400, t);
  filter.frequency.exponentialRampToValueAtTime(2600, t + 0.12);
};

S.jump = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;
  tone(260, t, 0.13, 'sine', 0.16, 220);
};

S.land = function (hard = 0.4) {
  if (!this.ready) return;
  const t = ctx.currentTime;
  noise(t, 0.09, 0.10 + hard * 0.14, 500, 1, 'lowpass');
  tone(90, t, 0.09, 'sine', 0.14 + hard * 0.14, -30);
};

S.dodge = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;
  const { filter } = noise(t, 0.16, 0.13, 1800, 3, 'bandpass');
  filter.frequency.setValueAtTime(2600, t);
  filter.frequency.exponentialRampToValueAtTime(500, t + 0.15);
};

S.grab = function () {
  if (!this.ready) return;
  tone(420, ctx.currentTime, 0.06, 'square', 0.09, 120);
};

S.throw_ = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;
  const { filter } = noise(t, 0.18, 0.14, 1200, 2.5, 'bandpass');
  filter.frequency.setValueAtTime(600, t);
  filter.frequency.exponentialRampToValueAtTime(3000, t + 0.16);
};

// Destruction, tinted by material.
S.smash = function (material = 'plastic', size = 0.5) {
  if (!this.ready) return;
  const t = ctx.currentTime;
  const p = Math.max(0, Math.min(1, size));
  if (material === 'glass') {
    for (let i = 0; i < 9; i++) {
      const tt = t + Math.random() * 0.16;
      tone(1600 + Math.random() * 2600, tt, 0.10 + Math.random() * 0.14, 'sine', 0.07, -600);
    }
    noise(t, 0.22, 0.16, 5200, 1, 'highpass');
  } else if (material === 'paper') {
    const { filter } = noise(t, 0.30, 0.13, 4200, 0.8, 'highpass');
    filter.frequency.exponentialRampToValueAtTime(1400, t + 0.28);
  } else if (material === 'metal') {
    noise(t, 0.14, 0.16, 3000, 1, 'bandpass');
    tone(320, t, 0.28, 'triangle', 0.14, -140);
    tone(690, t + 0.01, 0.22, 'triangle', 0.09, -260);
  } else {                                   // plastic / generic
    noise(t, 0.16, 0.18 + p * 0.1, 1600, 1, 'lowpass');
    tone(120, t, 0.13, 'square', 0.13, -60);
  }
};

S.coin = function (chain = 1) {
  if (!this.ready) return;
  const t = ctx.currentTime;
  // pentatonic, climbing with the chain so a long combo literally sounds better
  const scale = [523.25, 587.33, 659.25, 783.99, 880.0];
  const n = scale[Math.min(scale.length - 1, chain - 1)] || 880;
  tone(n, t, 0.10, 'triangle', 0.16);
  tone(n * 2, t + 0.015, 0.09, 'sine', 0.09);
};

S.chain = function (n) {
  if (!this.ready) return;
  const t = ctx.currentTime;
  const base = 330 * Math.pow(1.0595, Math.min(24, n * 2));
  tone(base, t, 0.13, 'triangle', 0.17);
  tone(base * 1.5, t + 0.05, 0.15, 'sine', 0.12);
  tone(base * 2, t + 0.10, 0.20, 'sine', 0.09);
};

S.coffee = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;
  const { filter } = noise(t, 0.55, 0.10, 900, 0.7, 'bandpass');
  filter.frequency.setValueAtTime(600, t);
  filter.frequency.linearRampToValueAtTime(1500, t + 0.5);
  tone(880, t + 0.5, 0.12, 'sine', 0.10, 300);
};

S.alarm = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;
  for (let i = 0; i < 3; i++) {
    tone(760, t + i * 0.24, 0.14, 'square', 0.11);
    tone(560, t + i * 0.24 + 0.12, 0.12, 'square', 0.11);
  }
};

S.bossRoar = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;
  tone(90, t, 0.65, 'sawtooth', 0.20, -40);
  tone(136, t + 0.02, 0.55, 'sawtooth', 0.13, -50);
  const { filter } = noise(t, 0.6, 0.13, 700, 1.2, 'lowpass');
  filter.frequency.exponentialRampToValueAtTime(200, t + 0.55);
};

S.ui = function (up = true) {
  if (!this.ready) return;
  const t = ctx.currentTime;
  tone(up ? 660 : 440, t, 0.07, 'triangle', 0.11, up ? 120 : -80);
};

S.promote = function () {
  if (!this.ready) return;
  const t = ctx.currentTime;
  [523.25, 659.25, 783.99, 1046.5].forEach((f, i) =>
    tone(f, t + i * 0.11, 0.32, 'triangle', 0.15));
};

// ---------------------------------------------------------------- music
// A two-bar loop scheduled a little ahead of playback. Deliberately plain and
// low in the mix: office muzak that gets more agitated as the boss does.
let musicTimer = null;
let step = 0;
let nextTime = 0;
let tension = 0;

const BASS = [0, 0, 3, 3, 5, 5, 3, 3, 0, 0, -2, -2, -4, -4, -2, -2];
const LEAD = [12, null, 15, null, 14, null, 12, null, 10, null, 12, null, 15, null, 17, null];
const ROOT = 110;                             // A2
const semi = n => ROOT * Math.pow(2, n / 12);

S.setTension = function (v) { tension = Math.max(0, Math.min(1, v)); };

S.startMusic = function () {
  if (!ctx || musicTimer || !this.musicOn) return;
  musicGain.gain.cancelScheduledValues(ctx.currentTime);
  musicGain.gain.setValueAtTime(0.0001, ctx.currentTime);
  musicGain.gain.exponentialRampToValueAtTime(0.5, ctx.currentTime + 1.5);
  nextTime = ctx.currentTime + 0.1;
  musicTimer = setInterval(() => this._pump(), 60);
};

S.stopMusic = function () {
  if (musicTimer) { clearInterval(musicTimer); musicTimer = null; }
  if (musicGain && ctx) {
    musicGain.gain.cancelScheduledValues(ctx.currentTime);
    musicGain.gain.setValueAtTime(musicGain.gain.value, ctx.currentTime);
    musicGain.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + 0.5);
  }
};

S._pump = function () {
  if (!ctx) return;
  const spb = 60 / (96 + tension * 34) / 2;          // eighth notes, faster under pressure
  while (nextTime < ctx.currentTime + 0.35) {
    const t = nextTime;
    const i = step % 16;

    // bass
    const bo = ctx.createOscillator();
    bo.type = 'triangle';
    bo.frequency.value = semi(BASS[i]);
    const bg = ctx.createGain();
    bg.gain.setValueAtTime(0.0001, t);
    bg.gain.exponentialRampToValueAtTime(0.22, t + 0.01);
    bg.gain.exponentialRampToValueAtTime(0.0001, t + spb * 0.9);
    bo.connect(bg); bg.connect(musicGain);
    bo.start(t); bo.stop(t + spb);

    // lead, thinner and only on the offbeats
    const ln = LEAD[i];
    if (ln !== null) {
      const lo = ctx.createOscillator();
      lo.type = tension > 0.6 ? 'square' : 'sine';
      lo.frequency.value = semi(ln);
      const lg = ctx.createGain();
      lg.gain.setValueAtTime(0.0001, t);
      lg.gain.exponentialRampToValueAtTime(0.06 + tension * 0.05, t + 0.02);
      lg.gain.exponentialRampToValueAtTime(0.0001, t + spb * 1.6);
      lo.connect(lg); lg.connect(musicGain);
      lo.start(t); lo.stop(t + spb * 1.8);
    }

    // hat on every other eighth
    if (i % 2 === 0) {
      const h = noiseVoice(t, 0.03, 0.05 + tension * 0.04, 7000);
      h.connect(musicGain);
    }
    // kick on the bar
    if (i % 8 === 0) {
      const k = ctx.createOscillator();
      k.type = 'sine';
      k.frequency.setValueAtTime(120, t);
      k.frequency.exponentialRampToValueAtTime(45, t + 0.11);
      const kg = ctx.createGain();
      kg.gain.setValueAtTime(0.0001, t);
      kg.gain.exponentialRampToValueAtTime(0.3, t + 0.008);
      kg.gain.exponentialRampToValueAtTime(0.0001, t + 0.16);
      k.connect(kg); kg.connect(musicGain);
      k.start(t); k.stop(t + 0.2);
    }

    nextTime += spb;
    step++;
  }
};

function noiseVoice(t, dur, peak, hz) {
  if (!noiseBuf) {
    noiseBuf = ctx.createBuffer(1, ctx.sampleRate * 1.2, ctx.sampleRate);
    const d = noiseBuf.getChannelData(0);
    for (let i = 0; i < d.length; i++) d[i] = Math.random() * 2 - 1;
  }
  const s = ctx.createBufferSource();
  s.buffer = noiseBuf;
  const f = ctx.createBiquadFilter();
  f.type = 'highpass';
  f.frequency.value = hz;
  s.connect(f);
  const g = ctx.createGain();
  g.gain.setValueAtTime(0.0001, t);
  g.gain.exponentialRampToValueAtTime(peak, t + 0.004);
  g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
  f.connect(g);
  s.start(t, Math.random() * 0.4);
  s.stop(t + dur + 0.05);
  return g;
}
